version: '3'

services:
  php:
    build: ./docker/php
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    working_dir: /app
    command: "php -S 0.0.0.0:8080"

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-checkbox}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: